[2020-12-21 15:10:24,639] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: loan_prediction_train_model.preprocess_data 2020-12-21T15:06:04.546570+00:00 [queued]>
[2020-12-21 15:10:24,654] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: loan_prediction_train_model.preprocess_data 2020-12-21T15:06:04.546570+00:00 [queued]>
[2020-12-21 15:10:24,655] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-12-21 15:10:24,655] {taskinstance.py:867} INFO - Starting attempt 5 of 6
[2020-12-21 15:10:24,656] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-12-21 15:10:24,666] {taskinstance.py:887} INFO - Executing <Task(LivyBatchOperator): preprocess_data> on 2020-12-21T15:06:04.546570+00:00
[2020-12-21 15:10:24,670] {standard_task_runner.py:53} INFO - Started process 33361 to run task
[2020-12-21 15:10:24,729] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: loan_prediction_train_model.preprocess_data 2020-12-21T15:06:04.546570+00:00 [running]> dcb43f18a24b
[2020-12-21 15:10:24,751] {logging_mixin.py:112} INFO - [2020-12-21 15:10:24,750] {batch.py:214} INFO - Submitting the batch to Livy... Payload:
{
  "file": "file:///dist/main.py",
  "args": [
    "-job=preprocess_data",
    "-phase=train",
    "-mode=aws",
    "-awsKey=AKIAUW4FKHTMR2UR3INH",
    "-awsSecretKey=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",
    "-s3Bucket=alanchn31-loan-default-prediction"
  ],
  "pyFiles": [
    "file:///dist/src.zip"
  ],
  "name": "preprocess_data_scheduled__2020-12-21T15:06:04.546570+00:00"
}
[2020-12-21 15:10:24,760] {logging_mixin.py:112} INFO - [2020-12-21 15:10:24,758] {base_hook.py:84} INFO - Using connection to: id: livy. Host: 3.238.254.96, Port: 8998, Schema: None, Login: None, Password: None, extra: None
[2020-12-21 15:10:24,762] {logging_mixin.py:112} INFO - [2020-12-21 15:10:24,762] {http_hook.py:136} INFO - Sending 'POST' to url: http://3.238.254.96:8998/batches
[2020-12-21 15:10:24,772] {logging_mixin.py:112} INFO - [2020-12-21 15:10:24,772] {http_hook.py:150} ERROR - HTTP error: Bad Request
[2020-12-21 15:10:24,772] {logging_mixin.py:112} INFO - [2020-12-21 15:10:24,772] {http_hook.py:151} ERROR - {"msg":"Duplicate session name: Some(preprocess_data_scheduled__2020-12-21T15:06:04.546570+00:00) for session 4"}
[2020-12-21 15:10:24,781] {taskinstance.py:1128} ERROR - 400:Bad Request
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 148, in check_response
    response.raise_for_status()
  File "/opt/bitnami/python/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://3.238.254.96:8998/batches

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/airflow/plugins/airflow_livy/batch.py", line 165, in execute
    self.submit_batch()
  File "/usr/local/airflow/plugins/airflow_livy/batch.py", line 218, in submit_batch
    LIVY_ENDPOINT, json.dumps(payload), headers
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 137, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 181, in run_and_check
    self.check_response(response)
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 152, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 400:Bad Request
[2020-12-21 15:10:24,782] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2020-12-21 15:10:34,633] {logging_mixin.py:112} INFO - [2020-12-21 15:10:34,633] {local_task_job.py:103} INFO - Task exited with return code 1
