[2020-12-22 12:50:59,902] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: loan_prediction_train_model.preprocess_data 2020-12-22T12:43:23.210460+00:00 [queued]>
[2020-12-22 12:50:59,920] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: loan_prediction_train_model.preprocess_data 2020-12-22T12:43:23.210460+00:00 [queued]>
[2020-12-22 12:50:59,920] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-12-22 12:50:59,920] {taskinstance.py:867} INFO - Starting attempt 3 of 6
[2020-12-22 12:50:59,920] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-12-22 12:50:59,932] {taskinstance.py:887} INFO - Executing <Task(LivyBatchOperator): preprocess_data> on 2020-12-22T12:43:23.210460+00:00
[2020-12-22 12:50:59,935] {standard_task_runner.py:53} INFO - Started process 11772 to run task
[2020-12-22 12:50:59,993] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: loan_prediction_train_model.preprocess_data 2020-12-22T12:43:23.210460+00:00 [running]> dcb43f18a24b
[2020-12-22 12:51:00,016] {logging_mixin.py:112} INFO - [2020-12-22 12:51:00,016] {batch.py:214} INFO - Submitting the batch to Livy... Payload:
{
  "file": "local:/tmp/airflowtmpqsaf8yls/usr/local/airflow/dist/main.py",
  "args": [
    "-job=preprocess_data",
    "-phase=train",
    "-mode=aws",
    "-awsKey=AKIAUW4FKHTMR2UR3INH",
    "-awsSecretKey=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",
    "-s3Bucket=alanchn31-loan-default-prediction"
  ],
  "pyFiles": [
    "local:/tmp/airflowtmpqsaf8yls/usr/local/airflow/dist/src.zip"
  ],
  "name": "preprocess_data_scheduled__2020-12-22T12:43:23.210460+00:00"
}
[2020-12-22 12:51:00,028] {logging_mixin.py:112} INFO - [2020-12-22 12:51:00,026] {base_hook.py:84} INFO - Using connection to: id: livy. Host: http://ec2-3-238-254-96.compute-1.amazonaws.com, Port: 8998, Schema: None, Login: None, Password: None, extra: None
[2020-12-22 12:51:00,030] {logging_mixin.py:112} INFO - [2020-12-22 12:51:00,030] {http_hook.py:136} INFO - Sending 'POST' to url: http://ec2-3-238-254-96.compute-1.amazonaws.com:8998/batches
[2020-12-22 12:52:45,431] {logging_mixin.py:112} INFO - [2020-12-22 12:52:45,430] {local_task_job.py:167} WARNING - State of this instance has been externally set to up_for_retry. Taking the poison pill.
[2020-12-22 12:52:45,433] {helpers.py:322} INFO - Sending Signals.SIGTERM to GPID 11772
[2020-12-22 12:52:45,434] {taskinstance.py:941} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-12-22 12:52:45,440] {taskinstance.py:1128} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/airflow/plugins/airflow_livy/batch.py", line 165, in execute
    self.submit_batch()
  File "/usr/local/airflow/plugins/airflow_livy/batch.py", line 218, in submit_batch
    LIVY_ENDPOINT, json.dumps(payload), headers
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 137, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/hooks/http_hook.py", line 178, in run_and_check
    allow_redirects=extra_options.get("allow_redirects", True))
  File "/opt/bitnami/python/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/bitnami/python/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/bitnami/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/bitnami/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/bitnami/python/lib/python3.6/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/bitnami/python/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/bitnami/python/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/bitnami/python/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/bitnami/python/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/bitnami/python/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/opt/bitnami/python/lib/python3.6/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/opt/bitnami/python/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/bitnami/python/lib/python3.6/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
  File "/opt/bitnami/python/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 943, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-12-22 12:52:45,444] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2020-12-22 12:52:45,460] {helpers.py:288} INFO - Process psutil.Process(pid=11772, status='terminated', exitcode=1, started='12:50:59') (11772) terminated with exit code 1
[2020-12-22 12:52:50,426] {logging_mixin.py:112} INFO - [2020-12-22 12:52:50,426] {local_task_job.py:103} INFO - Task exited with return code 1
